### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Pierstoval**
Pearson website is no longer the default used for the certification

Ping @javiereguiluz to see if it's valid 👍

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Awww, I have shared feelings about it.

Every person that has tried the certification is not allowed to contribute to Certificationy (as asked some years ago by @fabpot).

I know you are certified and @javiereguiluz too: as I have tried the certification too I'm also not allowed to contribute xD.

So, even if I accept the pull request: am I allowed to merge it? /c @fabpot

I don't want any trouble 👼

**Comment by fabpot** [comment]
Changes look good to me.

**Comment by Pierstoval** [comment]
I think contribution should probably be limited to questions, but IMO that's not the point of this PR, it should be okay for this part at least 😄

**Comment by 20uf** [comment]
Perfect, I am merging then :)
Thanks @Pierstoval

**Comment by mickaelandrieu** [comment]
Thanks everyone 👍

**Pull request merged**
