### PR TITLE
Added xlsx version of the questions. Unhide Column E to reveal the an…

### PR DESCRIPTION
**Pull request by mgill2190**
…swers.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello, what is the use case? AFAIK we don't have an xlsx parser for now :)

**Comment by mgill2190** [comment]
As a user, I wanted to use your questions to test myself but couldnt because the answers were there and there was no way to hide them. I have created an xlsx version of the questions so you can hide the answers (in column E) and this PR is to share the xlsx with everyone else.

**Comment by mickaelandrieu** [comment]
the main issue here for me is that we need to keep the xlxs file in sync with yaml file... we have a sort of flashcards system, but not the adaptor for decks nor the cli app.

Don't close your pull request I need to think about it  and thanks for your contribution :+1:

**Comment by mgill2190** [comment]
Fair point, its there if you want it.

**Pull request closed without merging**
