### PR TITLE
Kernel parameter doesn't exist

### PR DESCRIPTION
**Pull request by oktapodia**
The kernel parameter doesn't exist in the container ;)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Agree, this is a service.

**Comment by oktapodia** [comment]
fixed :)

**Comment by mickaelandrieu** [comment]
thanks @oktapodia I'll hope you will become certified, but not too much because you won't be able to contribute then :cat:

**Comment by oktapodia** [comment]
Thank you ;)

**Pull request merged**
