### PR TITLE
Update php.yml

### PR DESCRIPTION
**Pull request by FredoVelcro**
Fix escaping on namespaces

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
thx !

**Comment by FredoVelcro** [comment]
you're welcome ! ;)

**Comment by FredoVelcro** [comment]
Will http://www.certificationy.com be updated to reflect the changes ?

**Comment by mickaelandrieu** [comment]
This website is not related to this organisation, but I guess @ProPheT777 use our data.

**Pull request merged**
