### PR TITLE
Syncing from ProPheT777/certificationy-data

### PR DESCRIPTION
**Pull request by lepiaf**
Hi,

I find out that I create some question on https://github.com/ProPheT777/certificationy-data that are not in this set of question because there are two different project.

I would like to "sync" my question into this project.

Next time I will open PR on both project.

Thierry

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
thank you for this contribution :) and btw thank you @ProPheT777 (too bad you did your "own" deck)

**Comment by ProPheT777** [comment]
Yep I know, It was create when data in certificationy was coupled to the core lib :( May be we can find a moment to speak about that and find a solution to give consistent repo(s) and interoperable (certificationy-cli and web-platform). Like in the past i'm open of the discussion.

**Comment by mickaelandrieu** [comment]
@ProPheT777 of course I'm open too.

As you can see now, all "decks" are totaly uncoupled, so please free to suggest some improvements to make them more operable to your platform. :+1:

**Comment by ProPheT777** [comment]
Nice to hear.

The only problematic thing is how keep :

- https://github.com/ProPheT777/certificationy-data/blob/master/symfony2/contributing_en.html.twig
- https://github.com/ProPheT777/certificationy-data/blob/master/symfony2/context.yml

When these files are mandatory for web platform and also coupled to the data ?

**Comment by mickaelandrieu** [comment]
hmm, maybe the context can have a new field with the path of the deck ?

Maybe you can uncouple the "level" declaration from data, the context can accept a new field "deck" with the path of the deck ? I'm not sure.

I will take a look to the web platform and I come back with some ideas (I hope) :)

**Pull request merged**
